### ISSUE TITLE
Toasts component should be a hook

### ISSUE THREAD

**Issue by lisandro52** [the-coding-pie/workflow#1]
https://github.com/the-coding-pie/workflow/blob/0eb8ffdf760e127cfb258016b69acfc9848ba1ba/client/src/components/Toasts/Toasts.tsx#L8

A good rule of thumb is that whenever you see a FuncComponent returning null or a React.Fragment, but still having logic inside, that component should probably be a hook with a bit of refactoring.

In this case, you can have a new hook, `useToast`, which returns several functions: `showWarning`, `showError`, `showInfo`, or even a generic one in case those aren't enough, `showToast`. 
Each of those functions can call the `toast` function from `react-toastify` based on the parameters sent by the caller, without any extra components or multiple `ifs`. If you give me a couple of hours, I can make a basic example of that, or you can try something in the meantime.

**Comment by lisandro52** [comment]
The `useToast` hook could look something like this:

```jsx
import React, { useCallback } from 'react';
import { v4 as uuidv4 } from 'uuid';
import { toast } from "react-toastify";

const useToast = () => {
  const showError = useCallback(
    (text: string) => {
      toast.error(text, {
        toastId: uuidv4(),
      });
    },
    []
  );

  const showWarning = useCallback(
    (text: string) => {
      toast.warn(text, {
        toastId: uuidv4(),
      });
    },
    []
  );

  /// ... The rest of your msgs

  return { showError, showWarning }
}

export default useToast;
```

`uuid` is a small useful library that generates random ids that are perfect for this kind of use.
Note that we don't need Redux either! One less slice to configure and setup, and the API to use the hook is simple and clearly shows its intent.
To use the hook to show a warning, for example, you can do something like this:
```jsx
const { showWarning } = useToast();
showWarning("You shouldn't be doing that!");
```

**Comment by the-coding-pie** [comment]
This seems like a good refactoring. 

But for the uuid part, I intendely avoided it, because I wanted to avoid toasts duplication. For example, if there is already a toast with `kind: ERROR` and `msg: "This is an error"`, at that time, if another action caused the same toast to originate, I don't wanted to show that on the screen, because there is already a toast of the same kind exists on the screen at that given time. 

Except the uuid part, taking out toast from redux state and moving out to a hook sounds good to me.

**Comment by the-coding-pie** [comment]
Hey buddy, this approach is good, but there is a drawback. It cannot be called from outside a react component, because it is a hook right?

**Comment by lisandro52** [comment]
> Hey buddy, this approach is good, but there is a drawback. It cannot be called from outside a react component, because it is a hook right?

Yeah, per the Rules of Hooks, you can call hooks only from inside functional components or from other hooks. Why would you want to call a toast from something that's not one of these scenarios?

**Comment by aravind-k28** [comment]
Maybe you may have to add a toast from axiosInterceptor when something fails. In that case I may define the axiosInterceptor in its own file. So in that case I wont be able to add a toast by calling the hook, right?

By the way this is also my account(account of the-coding-pie, same person here :))

**Comment by lisandro52** [comment]
> Maybe you may have to add a toast from axiosInterceptor when something fails. In that case I may define the axiosInterceptor in its own file. So in that case I wont be able to add a toast by calling the hook, right?
> 

Yeah, that might be a case. But you could also catch the exception on the hook that's calling axios, so you can also update your data accordingly, and not on some obscure interceptor that shouldn't be tampering with the flow of the data.

Again, React isn't opinionated in these cases, you can do whatever you want with it and that's the beauty of it (and its biggest problem on a large app). I'm just nudging you on what I consider is best practice.

**Comment by the-coding-pie** [comment]
Yeah sounds good. Using react only things is always good to keep bundle size low as well as increase speed. 

I tried this approach in my new app, it is working fine. I haven't encountered any scenarios like where i have to use toast outside component. But i hope even if i encounter such a situation, i will be able to move forward with the same approach. Let's see.

By the way Thank you my friend for showing your interest in this topic!
