### ISSUE TITLE
Regarding Google App Password for authentication

### ISSUE THREAD

**Issue by Pratik-Nawale** [the-coding-pie/workflow#2]
Unable and obtain APP_SPECIFIC_PASSWORD from google, the app password option is not available for Gmail, is there any alternative?

**Comment by the-coding-pie** [comment]
I guess still we can get it. Check this link if it is useful or not -> https://support.google.com/accounts/answer/185833?hl=en#zippy=%2Capp-passwords-revoked-after-password-change%2Cwhy-you-may-need-an-app-password

**Comment by Pratik-Nawale** [comment]
I have gone through it, but still the "_app password_" option is not visible, even after enabling 2 step verification, would you mind helping me through it?

**Comment by the-coding-pie** [comment]
Ok Pratik, let me check myself and get back to you

**Comment by Pratik-Nawale** [comment]
Ok @the-coding-pie thank you so much, it will be very helpful.

**Comment by Pratik-Nawale** [comment]
I found a way to set app password if the option is not visible, just visit this [link](https://myaccount.google.com/apppasswords) or
"_https://myaccount.google.com/apppasswords_", paste the **APP_SPECIFIC _PASSWORD** in the **GMAIL-PASSWORD** field of the **.env** file of the **server**
